### ISSUE TITLE
Runtime error failing to import `idc_index._version`

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#69]
This is happening with current main

```
Traceback (most recent call last):
  File "/Users/af61/Downloads/idc-index/./download_manifest.py", line 2, in <module>
    from idc_index import index
  File "/Users/af61/Downloads/idc-index/idc_index/__init__.py", line 10, in <module>
    from ._version import version as __version__
ModuleNotFoundError: No module named 'idc_index._version'
```

**Comment by fedorov** [comment]
@jcfr do you have any ideas what might be causing this? 

We don't even have a way to reproduce this error. It happens in some python environments.

**Comment by jcfr** [comment]
Looks like the script `download_manifest.py` is being executed from a directory itself containing a sub folder called `idc_index` ? This likely leads to the wrong package being imported.
